name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ seccrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: test pwd
        run: 
          sshpass -e ssh -o stricthostkeychecking=no ${{ seccrets.APP_USER }}@${{ seccrets.APP_HOST }} 'pwd'
