name: ssh-pipeline

on:
  push:
    branches:
      - main

env:
  APP_DIR: ${{ secrets.APP_DIR }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.APP_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.APP_HOST }}
                  
      - name: Deploy
        run:
          ssh deploy 'pwd'
