name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.APP_HOST }}
          user: ${{ secrets.APP_USER }}
          pass: ${{ secrets.APP_PASS }}
          run: |
            pwd
