name: ssh-pipeline

on:
  push:
    branches:
      - main

env:
  APP_DIR: ${{ secrets.APP_DIR }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Setup SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ SERVER_SSH_KEY }}
          ssh-host: ${{ APP_HOST }}
      
      - name: Deploy
        run:
          ssh ${{ secrets.APP_HOST }}
          pwd
