name: ssh-pipeline

on:
  push:
    branches:
      - main

env:
  APP_DIR: ${{ secrets.APP_DIR }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  
      - name: Deploy
        run:
          ssh ${{ secrets.APP_HOST }}
          pwd
