name: ssh-pipeline

on:
  push:
    branches:
      - main

env:
  APP_DIR: ${{ secrets.APP_DIR }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1.0.1
        with:
          host: ${{ secrets.APP_HOST }}
          private-key: ${{ secrets.SERVER_SSH_KEY }}
      
      - name: Deploy
        run:
          ssh ${{ secrets.APP_HOST }}
          pwd
